In [ ]:
from cleanfid import fid
fdir1 = 'retrieve/retrieve_dog/photo_of_a_dog'
fdir2 = 'logs/2023-03-26T12-52-38_dog-sdv4/samples'
score = fid.compute_kid(fdir1, fdir2)
score

# Compute new_concept_similarity


In [ ]:
from sklearn.manifold import TSNE
import numpy as np
from matplotlib import pyplot as plt
import torch

def to_array(dl):
    if isinstance(dl[0],torch.Tensor):
        out = [d.cpu().numpy() for d in dl]
        return np.stack(out, axis=0)
    elif isinstance(dl[0],np.ndarray):
        return np.stack(dl, axis=0)
    else:
        raise NotImplementedError('not supported type')

def process_data(path):
    out={}
    data = torch.load(path)
    c_sim = to_array(data.pop('c_sim_global'))
    c_new_global =  to_array(data.pop('c_new_global'))
    c_reg_global = to_array(data.pop('c_reg_global'))
    keys = data.keys()
    out['c_sim'] = c_sim
    # out['c_sim'] = c_sim
    for key in keys:
        weights = to_array(data[key])
        start_weight =  weights[0]
        delta_weights = weights - np.expand_dims(start_weight, axis=0)       
        # distance = np.sum(delta_weights,axis=(1,2))
        distance = np.linalg.norm(delta_weights,axis=(1,2))
        out[key + '_distance'] = distance
        # print(distance)
        # print(np.transpose(weights[1],(1,0)).shape)
        c_mapped_new = [c_n @ np.transpose(weights[i],(1,0)) for i,c_n in zip(range(len(weights)),c_new_global)]
        c_mapped_new = np.stack(c_mapped_new, axis=0)
        c_mapped_reg = [c_reg_global @ np.transpose(weights[i],(1,0)) for i in range(len(weights))]
        c_mapped_reg = np.concatenate(c_mapped_reg, axis=0)
        # print(c_mapped_reg.shape)
        out[key + '_c_mapped_new'] = c_mapped_new
        out[key + '_c_mapped_reg'] = c_mapped_reg
    return out



def draw_line(x1,x2 =None,x3= None,x4=None):
    fig, ax = plt.subplots()
    ax.plot(x1, marker='o', linestyle='-', color='r',label = '<new> + prompt')
    if x2 is not None:
        ax.plot(x2, marker='o', linestyle='--', color='g',label = '<new> + prompt, reg')
    if x3 is not None:
        ax.plot(x3, marker='s', linestyle='-', color='r',label = '<new>')
    if x4 is not None:
        ax.plot(x4, marker='s', linestyle='--', color='g',label = '<new>, reg')
    plt.legend( loc='upper right',fontsize=7)
    plt.xticks(np.arange(0,len(x1) +1),fontsize=7)
    plt.show()

path = 'logs/2023-03-27T09-11-12_dog_realReg-sdv4/statics.pt'
path_reg = 'logs/2023-03-27T09-10-44_dog_genReg-sdv4/statics.pt'
out = process_data(path)
out_reg = process_data(path_reg)
c_mapped_new = []
c_mapped_reg = []
distance = []
for key in out_reg.keys():
    if 'distance' in key:
        distance.append(key)
    elif 'c_mapped_new' in key:
        c_mapped_new.append(key)
    elif 'c_mapped_reg' in key:
        c_mapped_reg.append(key)
c_mapped_reg = sorted(c_mapped_reg)
c_mapped_new = sorted(c_mapped_new)
distance = sorted(distance) 


N = len(distance)
n = 4 # size of each array

fig, axs = plt.subplots(N // 4 + (N % 4 != 0), 4,figsize=(10, 8))
for i in range(N):
    data = out[distance[i]]
    data_reg = out_reg[distance[i]]
    data_c_reg = out_c_reg[distance[i]]
    axs[i // 4][i % 4].plot(data, marker='o', linestyle='-', color='r',linewidth=1,label = 'real reg.')
    axs[i // 4][i % 4].plot(data_reg, marker='o', linestyle='-', color='b',linewidth=1,label = 'gen. reg.')
    axs[i // 4][i % 4].plot(data_c_reg, marker='o', linestyle='-', color='g',linewidth=1,label = 'gen. reg.')
    # plt.xticks(fontsize=3)
    # plt.yticks(fontsize=3)
plt.savefig('distance.png',dpi=300)
plt.show()

我给你一个句子，需要你帮助我生成100句语义相近的句子，生成的句子内容可以拓展和补充。以下是一个例子，我给你一句“photo of a dog", 你可以生成“photo of a corgi on the beach"，或“A yellow dog rides a skateboard on the street”，如果明白了需求，只需要回复“OK”

In [ ]:
import os,torch
import copy
path = 'logs/2023-04-03T16-00-34_dogreg_1_scale0.01_a_dog/checkpoints/'
ckpts = []
for name in os.listdir(path):
    path_file = os.path.join(path,name)
    ckpt = dict(torch.load(path_file, map_location='cpu')['state_dict'])
    keys = ckpt.keys()
    for k in list(keys):
        if ('attn2.to_k' in k or 'attn2.to_k0' in k or 'attn2.to_v0' in k or 'attn2.to_v' in k):
            pass 
        else:
            ckpt.pop(k)
    ckpts.append(ckpt)
epoch_ckpt = ckpts[-1]

delta = epoch_ckpt['model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight'] - epoch_ckpt['model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k0.weight'] 
flatten_delta2 = delta.flatten()
import matplotlib.pyplot as plt
fig, ax= plt.subplots(figsize=(6,6))
ax.hist(flatten_delta,bins=100,label=r"$\alpha = 1$,$\beta$ = 1")
ax.hist(flatten_delta2,bins=100,label=r"$\alpha$ = 10,$\beta$ = 1")
plt.legend()
plt.show()

# SVD compression

In [ ]:
W = epoch_ckpt['model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight']
W0 = torch.load('Stable-diffusion/sd-v1-4-full-ema.ckpt',map_location='cpu')['state_dict']['model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight']
delta = W - W0
u, s, vt = torch.linalg.svd(delta.clone())

# Get_deltas

In [25]:
import glob
import os
for dir in os.listdir('logs'):
    path = os.path.join('logs',dir)
    os.system(f'python src2/get_deltas.py --path {path}')

logs/2023-04-13T08-02-21_barn_classBias_reg0.1-0.1_scale0-0/checkpoints/epoch=000022-step=000000199.ckpt
['model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight', 'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k0.weight', 'model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v0.weight', 'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight', 'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k0.weight', 'model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v0.weight', 'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight', 'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight', 'model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k0.weight'

In [ ]:
from src2.custom_modules import FrozenCLIPEmbedderWrapper as CLIP2
from src.custom_modules import FrozenCLIPEmbedderWrapper as CLIP1
from transformers import CLIPTokenizer, CLIPTextModel
import torch
clip1 = CLIP2("<new1>",concept_classes = ["<new1> tortoise plushy"],device='cuda')
# tokenizer = CLIPTokenizer.from_pretrained('openai/clip-vit-large-patch14')

In [ ]:
clip1.tokenize('<new1>')
new_token = clip1.transformer.get_input_embeddings().weight.data[49408]

In [ ]:
from src2.custom_modules import FrozenCLIPEmbedderWrapper as CLIP
from transformers import CLIPTokenizer, CLIPTextModel
import torch
clip = CLIP("<new1>",device='cpu')

# compute modified similarity

In [ ]:
import glob
import numpy as np
import re
dir = 'logs/2023-04-08T03-32-12_tortoise_plushyreg_0.1_scale0_a_tortoise_plushy_ridge_onlyK_noblip'
matchObj = re.match(r'.*(tortoise_plushy|teddybear|cat|dog).*', dir, re.M|re.I)
concept = matchObj[1].replace('_',' ')
print(concept)
sims = []
for delta_ckpt in sorted(glob.glob(dir+'/checkpoints/*.ckpt')):
    if delta_ckpt is not None:
        delta_st = torch.load(delta_ckpt,map_location='cpu')
        embed = None
        if 'embed' in delta_st['state_dict']:
            embed = delta_st['state_dict']['embed'].reshape(-1,768)
            del delta_st['state_dict']['embed']
        clip.transformer.text_model.embeddings.token_embedding.weight.data[-embed.shape[0]:] = embed
    a = clip.encode_text([f'<new1> {concept}'])
    b = clip.encode_text([f'{concept}'])
    sim = torch.cosine_similarity(a[1],b[1])
    sims.append(np.round(sim.item(),4))
print(sims)

In [ ]:
from src2.custom_modules import FrozenCLIPEmbedderWrapper as CLIP
clip = CLIP("<new1>",device='cpu')

In [ ]:
output = clip.encode(['dog','a dog','red dog','two dog'])

In [ ]:
print(torch.norm(output[0]))
# print(output[:,20:21,:])
# print(output[:,2:3,:])

In [ ]:
import torch.nn as nn
class test(nn.Module):
    def __init__(self):
        super().__init__()
        self.ids = []
        self.params = {'a':nn.Parameter(torch.randn(1,1,1),requires_grad=True),
                        'b':nn.Parameter(torch.randn(1,1,1))}
        self.params2 = nn.Parameter(torch.randn(1,1,1),requires_grad=True)
        # self.embed = nn.Embedding(10,10)
        self.params3 = [nn.Parameter(torch.randn(1,1,1),requires_grad=True)]
    def forward(self, x, key):
        return x

In [ ]:
net = test()
torch.save(net.state_dict(),'test.pt')
a = torch.load('test.pt',map_location='cpu')
a 

In [ ]:
import torch
from transformers import CLIPVisionModel
from PIL import Image
import requests
from transformers import AutoProcessor, CLIPVisionModel,CLIPProcessor

version = "openai/clip-vit-large-patch14"
model = CLIPVisionModel.from_pretrained(version)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-large-patch14")


In [ ]:
from PIL import Image
import requests
from transformers import AutoProcessor, CLIPVisionModel

image = Image.open('data/dog/5.jpeg')

inputs = processor(images=image, return_tensors="pt")

outputs = model(**inputs)
last_hidden_state = outputs.last_hidden_state
pooled_output = outputs.pooler_output  # pooled CLS states

In [ ]:
_ ,a = clip.encode_text(["dog"]) 


In [ ]:
cat_0_0 = [0.7059, 0.7015, 0.7048, 0.7049, 0.7062]
cat_01_0 = [0.6662, 0.6095, 0.5932, 0.5752, 0.5783]
cat_10_0 = [0.6705, 0.5937, 0.5625, 0.524, 0.4937]
sim_cat = [0.7011, 0.6720]

bear_0_0 = [0.7568, 0.7575, 0.757, 0.7559, 0.7567]
bear_01_0 = [0.7401, 0.6886, 0.664, 0.6285, 0.6267]
bear_01_0 = [0.7377, 0.673, 0.6286, 0.5637, 0.5556]
sim_teddybear = [0.6466, 0.6668]

dog_0_0 = [0.6241, 0.6054, 0.6097, 0.608, 0.6343]
dog_01_0 = [0.5841, 0.5235, 0.5014, 0.51, 0.5088]
dog_01_0_onlyK = [0.6115, 0.5835, 0.5924, 0.5809]
sim_dog = [0.5982, 0.6258]

plushy_01_0_onlyK = [0.807, 0.7913, 0.7771, 0.7607, 0.7532]
plushy_01_0_onlyV = [0.8067, 0.79, 0.7706, 0.754, 0.7436]
sim_plushy = [0.7917, 0.802]

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
def draw_line2(x1,x2 =None,x3= None,x4=None,constant1=None,constant2=None):
    fig, ax = plt.subplots()
    ax.plot(x1, marker='*', linestyle='-', color='r',label = 'no reg.')
    if x2 is not None:
        ax.plot(x2, marker='o', linestyle='-', color='g',label = '0.1 text reg.')
    if x3 is not None:
        ax.plot(x3, marker='s', linestyle='-', color='b',label = '1.0 text reg.')
    if x4 is not None:
        ax.plot(x4, marker='s', linestyle='--', color='g',label = '<new>, reg')
    if constant1 is not None:
        # draw a horizontal line
        ax.axhline(y=constant1, color='r', linestyle='--',label = 'real reg.')
    if constant2 is not None:
        # draw a horizontal line
        ax.axhline(y=constant2, color='y', linestyle='--',label = 'gen. reg.')
        
    plt.legend( loc='best',fontsize=10)
    plt.xticks(np.arange(0,len(x1) +1),fontsize=7)
    plt.show()
draw_line2(cat_0_0,cat_01_0,cat_10_0,constant1 = sim_cat[0],constant2 = sim_cat[1])

In [ ]:
sim_dog_epoch = [0.5962,0.6115,0.5835,0.5924,0.5809]
sim_dog = [0.5982, 0.6258]

sim_tortoise_plushy_epoch = [0.8040, 0.7401,0.6886,0.6640,0.6285,0.6267]

sim_cat_epoch = [0.7061, 0.7401,0.6886,0.6640,0.6285,0.6267]
sim_cat = [0.7011, 0.6720, 0.6267]

sim_teddybear_epoch = [0.7455, 0.7401,0.6886,0.6640,0.6285,0.6267]
sim_teddybear = [0.7611, 0.7369, 0.6267]

In [ ]:
import re

str = "2023-04-05T10-16-22_tortoise_plushyreg_1_scale1_a_tortoise_plushy_ridge"
matchObj = re.match(r'.*_(.*)reg.*a_(.*)_(.*)', str, re.M|re.I)

if matchObj:
   print("matchObj.group(1) : ", matchObj.group(1))
   print("matchObj.group(2) : ", matchObj.group(2))
   print("matchObj.group(3) : ", matchObj.group(3))
else:
   print("No match!!")

file = 'logs/2023-04-05T15-42-14_catreg_0.1_scale0.1_a_cat_ridge/checkpoints/epoch=000011-step=000000399.ckpt'
out = re.match(r'.*step=0+(\d+).ckpt',file)

In [ ]:
from PIL import Image
import os

dirs = ['logs/logs_lds11/2023-04-12T09-01-16_tortoise_plushy_reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T08-49-20_tortoise_plushy_classBias_reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T04-10-18_tortoise_plushy_realReg__reg0.1-0.1_scale0-0','logs/logs_lds11/2023-04-12T05-53-28_tortoise_plushy_realReg_classBias_reg0.1-0.1_scale0-0', 'logs/logs_liox/2023-04-05T14-20-45_tortoise_plushy-sdv4','logs/logs_liox/2023-04-06T15-39-11_tortoise_plushy-sdv4']
profix = ['delta_epoch=last','delta_epoch=last','delta_epoch=last','last','delta_epoch=last','delta_epoch=last']
output_dir = 'output/tortoise_Classbias/'

os.makedirs(output_dir, exist_ok=True)
for filename in os.listdir(dirs[0]):
    if filename.endswith('.png') and filename.startswith(profix[0]):
        filename = filename.replace(profix[0],'')
        try:
            # print([(d + '/' + ''.join([p,filename])) for d,p in zip(dirs,profix)])
            images = [Image.open(d + '/' + ''.join([p,filename])) for d,p in zip(dirs,profix)]
        except:
            print("error",filename)
            continue
        widths, heights = zip(*(i.size for i in images))
        total_width = max(widths)
        max_height = sum(heights)
        new_im = Image.new('RGB', (total_width, max_height))
        x_offset = 0
        for im in images:
            new_im.paste(im, (0, x_offset))
            x_offset += im.size[1]
        new_im.save(os.path.join(output_dir, filename))
        print("saved",filename)

In [ ]:
import os
from PIL import Image
dirs = ['logs/logs_lds11/2023-04-12T08-10-40_cat_reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T07-56-34_cat_classBias_reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T03-25-09_cat_realReg__reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T05-30-17_cat_realReg_classBias_reg0.1-0.1_scale0-0','logs/logs_liox/2023-04-05T05-04-21_cat-sdv4','logs/logs_liox/2023-04-06T15-07-33_cat-sdv4']
profix = ['delta_epoch=last','delta_epoch=last','delta_epoch=last','last','delta_epoch=last','delta_epoch=last']
output_dir = 'output/cat_Classbias/'

os.makedirs(output_dir, exist_ok=True)
for filename in os.listdir(dirs[0]):
    if filename.endswith('.png') and filename.startswith(profix[0]):
        filename = filename.replace(profix[0],'')
        try:
            # print([(d + '/' + ''.join([p,filename])) for d,p in zip(dirs,profix)])
            images = [Image.open(d + '/' + ''.join([p,filename])) for d,p in zip(dirs,profix)]
        except:
            print("error",filename)
            continue
        widths, heights = zip(*(i.size for i in images))
        total_width = max(widths)
        max_height = sum(heights)
        new_im = Image.new('RGB', (total_width, max_height))
        x_offset = 0
        for im in images:
            new_im.paste(im, (0, x_offset))
            x_offset += im.size[1]
        new_im.save(os.path.join(output_dir, filename))
        print("saved",filename)

In [ ]:
dirs = ['logs/logs_lds11/2023-04-12T08-36-57_teddybear_reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T08-24-32_teddybear_classBias_reg0.1-0.1_scale0-0', 'logs/logs_lds11/2023-04-12T03-47-36_teddybear_realReg__reg0.1-0.1_scale0-0','logs/logs_lds11/2023-04-12T05-42-56_teddybear_realReg_classBias_reg0.1-0.1_scale0-0', 'logs/logs_liox/2023-04-05T05-15-20_teddybear-sdv4','logs/logs_liox/2023-04-06T15-24-25_teddybear-sdv4']
profix = ['delta_epoch=last','delta_epoch=last','delta_epoch=last','last','delta_epoch=last','delta_epoch=last']
output_dir = 'output/teddybear_classBias/'

os.makedirs(output_dir, exist_ok=True)
for filename in os.listdir(dirs[0]):
    if filename.endswith('.png') and filename.startswith(profix[0]):
        filename = filename.replace(profix[0],'')
        try:
            # print([(d + '/' + ''.join([p,filename])) for d,p in zip(dirs,profix)])
            images = [Image.open(d + '/' + ''.join([p,filename])) for d,p in zip(dirs,profix)]
        except:
            print("error",filename)
            continue
        widths, heights = zip(*(i.size for i in images))
        total_width = max(widths)
        max_height = sum(heights)
        new_im = Image.new('RGB', (total_width, max_height))
        x_offset = 0
        for im in images:
            new_im.paste(im, (0, x_offset))
            x_offset += im.size[1]
        new_im.save(os.path.join(output_dir, filename))
        print("saved",filename)

In [ ]:

import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

# Set up the grid
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)
x, y = np.meshgrid(x, y)

# Define the horizontal plane
z1 = np.zeros_like(x)
z1.fill(1.1)

# Define the Gaussian plane
z2 = np.exp(-(x**2 + y**2)/10)+0.7
# z3 = np.exp(-(x**2 + y**2)/0.02)

z2  = z2 

# Calculate the volume under the Gaussian plane
# vol_z2 = np.trapz(np.trapz(z2, x[0,:]), y[:,0])

# Adjust the height of the horizontal plane to match the volume under the Gaussian plane
# z1 = z1 + vol_z2 / (x.shape[0] * y.shape[1])

# Plot the planes
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x, y, z1, alpha =0.5)
ax.plot_surface(x, y, z2, alpha =0.5)

plt.show()

In [ ]:
import torch
a = torch.load('model.pt',map_location=torch.device('cpu'))
for key in a.keys():
    print(key)

In [20]:
from sklearn import linear_model
import numpy as np
clf = linear_model.Lasso(alpha=0.01)
X = np.random.rand(788, 768)
Y = np.random.rand(788, 1024)
clf.fit(X,Y)

print(clf.coef_)

print(clf.intercept_)

[[ 0. -0. -0. ... -0. -0. -0.]
 [ 0. -0.  0. ... -0.  0. -0.]
 [ 0. -0.  0. ... -0. -0.  0.]
 ...
 [-0. -0. -0. ... -0.  0.  0.]
 [-0.  0.  0. ...  0.  0. -0.]
 [-0. -0.  0. ... -0.  0. -0.]]
[0.4962561  0.50252373 0.4974778  ... 0.52378817 0.51950387 0.49100449]


In [22]:
clf.coef_.shape


(1024, 768)

In [13]:
from omegaconf import OmegaConf
config = OmegaConf.load("configs/custom-diffusion/finetune.yaml")

In [18]:
config.model.params.cond_stage_config.params = {}
config.model.params.cond_stage_config.params.concept_classes = [1]
config.model.params.cond_stage_config.params.concept_classes += [1]
a = [1] 
a += config.model.params.cond_stage_config.params.concept_classes

In [24]:
# if has attribute bias_strengths then use it, else use [0.0]
if hasattr(config.model.params.cond_stage_config.params, 'bias_strengths'):
    print(config.model.params.cond_stage_config.params.bias_strengths)

In [16]:
config.model.params.cond_stage_config.params.concept_classes
torch.load('logs/2023-04-13T17-29-57_dog_classBias_reg0.1-0.1_scale0-0/checkpoints/epoch=000019-step=000000199.ckpt',map_location='cpu')['state_dict'].keys()

odict_keys(['betas', 'alphas_cumprod', 'alphas_cumprod_prev', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'log_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod', 'posterior_variance', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'logvar', 'model.diffusion_model.time_embed.0.weight', 'model.diffusion_model.time_embed.0.bias', 'model.diffusion_model.time_embed.2.weight', 'model.diffusion_model.time_embed.2.bias', 'model.diffusion_model.input_blocks.0.0.weight', 'model.diffusion_model.input_blocks.0.0.bias', 'model.diffusion_model.input_blocks.1.0.in_layers.0.weight', 'model.diffusion_model.input_blocks.1.0.in_layers.0.bias', 'model.diffusion_model.input_blocks.1.0.in_layers.2.weight', 'model.diffusion_model.input_blocks.1.0.in_layers.2.bias', 'model.diffusion_model.input_blocks.1.0.emb_layers.1.weight', 'model.diffusion_model.input_blocks.1.0.emb_layers.1.bias', 'model.diffusion_model.input_blocks.1.0.ou